language: node_js
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "JPItJfyhzOOUUnbRCg1CxMX2QzJh+WGOLjtzxhWQJT3XQh7BbBdo2y/nXTp4fqSyWBfNkwbfkpb4BRBdMbWde7at1VKZuKxLDRtsyQTLx95lcqUVreU9m9TOY4EThp0Fscn26TF0c+3+yV7TzgU5MiN4FWE8f1b3yUGca17OJ2ckhMjMvJgCioz43N2KpK8EruJIFfCq8gVaE7fyvzNjmJsR7h6fNyhBrs+sBcgR3pH+Aj7r6FVPFg1rmHbZMJnbkYW45CAxKuA7d2/2t8eekC+tjqynO/4vF55z/AuFvO+mBeNpR539wwz5fLbLMZO8nNHpvfxCzZGu8V8EFjj+0AZP2vkWZp8uFmoHudnAHdfDiZxx1VpnAAhCMfQZLX6UylEF14Wn8s0ufepmuyGVXwxWA0jWa4B0EgWLNjHegipJvkjl7laDRJEfi8pJVnFVOvjjSVztdfBDL195QGtnED2Z9o/k1ffn6F+94KVb3UtRHbg+lTzXZeUhx8/DOmpzKddXrklXZ3QMyUzNYKoSU3JCJ/FbG4ZncreB0ko7N/juF3ZPTSVcvov2iyBkdMfOaS3t8g3T0CQZsF3t/nsE5R+4bq42kaeue2vZrFxtIKU5kGBXWWozEKZxu/WTl/MQslFv0up8nE+YA06bcSU1lnlgpt0dROkscxKeoESrE4Q="
  api_key: # f30d
    secure: "KI8KQSBMpasJgC3miPIXFzD9d0Ep31+9kaCOf1mDoPXwaaImS+Pc4hjssvJgpxtk+go3jtzfRTTuqbBfqWTXbJAGEsvBaT9rwJHKLOVZgPtGXdnmMthnOgkSDWa3XBrVBaqbOU0beJP82OH9h0OOgurhcaF46FNudNbYe7tpK1rY05+T3+0f8B0Tosqye684jzk088uqswD08I/PMm1UaTZhx0Bjq+FbKNQ4ayKcInrRwr5WpbS3jr7ennBy4qY0LW9K2/BUuqLGT1mkSXXUVWYY7Yef7eukIPglRATA+qa/yseterB2Pw5+gawwmZa+ef7Z+GUHWerZNhzZMKdnq+UJ37TcKbCFvDqnXl9oFvoLvkNlmUmcFPot2mWbC/RSD2So1jQxQqxrhFx/Hdivspx+Z42O4rEB+fcy3daq9tQZ+oW72SCuR2aalLhWM8lyAWI1Uk0diGc1DJ5/NtIsnGNaZnUxmiYAd2qRR1htknScD8vhLTHb00SFmtQ0JxnHq3QbMCIslePelZwguHX4czKCIgZkWR5lXUameTy424TMkXoEXCXXl08CZ+ipL116mhj9y6bwDqPd/ORWj85HpXMcBRQECCJK+9anlVyd6Gb6qZa7ZufvbYnYTa5LujG9jVN+SUvdk3CGXJngtiZdIM/+YCh8dh3ezs2Me8pvtKo="
  on:
    tags: true
    node: lts/*
